[phases.setup]
dotnet = "8.0" # Указание версии .NET SDK

[phases.build]
command = "dotnet publish --no-restore -c Release -o out"

[phases.start]
command = "./out/CVB" # Замените CVB на название вашего выходного файла, если оно отличается

[env]
DOTNET_SDK_VERSION = "8.0.100" # Принудительно укажите версию SDK
