name: Build and Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Укажите версию .NET SDK

      - name: Restore dependencies
        run: dotnet restore ./CVB/CVB.csproj

      - name: Build
        run: dotnet build ./CVB/CVB.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./CVB/CVB.csproj --no-build --verbosity normal
