name: Build and Deploy to Amvera

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.0'  # Задайте вашу версию .NET SDK

      - name: Restore dependencies
        run: dotnet restore ./CVB/CVB.csproj

      - name: Build
        run: dotnet build ./CVB/CVB.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./CVB/CVB.csproj --configuration Release --output ./publish

      - name: Deploy to Amvera
        # Этот шаг будет зависеть от того, какой метод развертывания поддерживает Amvera.
        # В документации к Amvera должно быть указано, какой метод развертывания использовать.
        # Например, здесь можно использовать SSH или API.
